### ISSUE TITLE
Management (Create, Read, Update, Delete)

### ISSUE THREAD

**Issue by hardingadonis** [hardingadonis/pezhi#2]
## Tasks:
- [x] Design the database (SQL)
  - [x] Export generation file for creating tables
  - [x] Export diagram image
