### ISSUE TITLE
Offline mode (Database file will stored local)

### ISSUE THREAD

**Issue by hardingadonis** [hardingadonis/pezhi#3]
## Tasks:
- [x] For default:
  - [x] Create `database.sqlite` in `root` folder if the database file is not found.
  - [x] Create all tables after creating `database.sqlite`.
  - [x] Close connections with the database file.
- [x] For user customization:
  - [x] Change the database file location.
  - [x] If a database file from user customization is not found, create it.
  - [x] Create all tables after creating a database file from user customization.
  - [x] Close connections with the database file.
- [x] Switch between `default` and `user customization`.
- [ ] #5
